chore(ci): update MacOS code signing for archive

diff --git a/.github/workflows/build_binaries.yml b/.github/workflows/build_binaries.yml
--- a/.github/workflows/build_binaries.yml
+++ b/.github/workflows/build_binaries.yml
@@ -292,7 +292,6 @@ jobs:
           echo "CARGO=cross" >> $GITHUB_ENV
 
       - name: Install and setup cargo-auditable
-        # if: ${{ ( startsWith(github.ref, 'refs/tags/v') ) && ( ! matrix.builds.cross ) }}
         if: ${{ ( ! matrix.builds.cross ) }}
         shell: bash
         run: |
@@ -384,23 +383,23 @@ jobs:
           path: "${{ env.MTS_SOURCE }}/*"
 
       - name: Build the macOS pkg
-        if: startsWith(runner.os,'macOS')
+        if: ${{ ( startsWith(runner.os,'macOS') ) && ( env.MACOS_APPLICATION_CERT != '' ) }}
         continue-on-error: true
         env:
           MACOS_KEYCHAIN_PASS: ${{ secrets.MACOS_KEYCHAIN_PASS }}
           MACOS_APPLICATION_ID: ${{ secrets.MACOS_APPLICATION_ID }}
           MACOS_APPLICATION_CERT: ${{ secrets.MACOS_APPLICATION_CERT }}
           MACOS_APPLICATION_PASS: ${{ secrets.MACOS_APPLICATION_PASS }}
-          MACOS_INSTALLER_ID: ${{ secrets.MACOS_INSTALLER_ID }}
-          MACOS_INSTALLER_CERT: ${{ secrets.MACOS_INSTALLER_CERT }}
-          MACOS_INSTALLER_PASS: ${{ secrets.MACOS_INSTALLER_PASS }}
+          # MACOS_INSTALLER_ID: ${{ secrets.MACOS_INSTALLER_ID }}
+          # MACOS_INSTALLER_CERT: ${{ secrets.MACOS_INSTALLER_CERT }}
+          # MACOS_INSTALLER_PASS: ${{ secrets.MACOS_INSTALLER_PASS }}
           MACOS_NOTARIZE_USERNAME: ${{ secrets.MACOS_NOTARIZE_USERNAME }}
           MACOS_NOTARIZE_PASSWORD: ${{ secrets.MACOS_NOTARIZE_PASSWORD }}
           MACOS_ASC_PROVIDER: ${{ secrets.MACOS_ASC_PROVIDER }}
         run: |
-          # set -xo pipefail
+          set -xo pipefail
           echo "${MACOS_APPLICATION_CERT}" | base64 --decode > application.p12
-          echo "${MACOS_INSTALLER_CERT}" | base64 --decode > installer.p12
+          # echo "${MACOS_INSTALLER_CERT}" | base64 --decode > installer.p12
           security create-keychain -p ${MACOS_KEYCHAIN_PASS} build.keychain
           security default-keychain -s build.keychain
           security unlock-keychain -p ${MACOS_KEYCHAIN_PASS} build.keychain
@@ -408,59 +407,82 @@ jobs:
             -t cert -f pkcs12 \
             -P ${MACOS_APPLICATION_PASS} \
             -T /usr/bin/codesign
-          security import installer.p12 -k build.keychain \
-            -t cert -f pkcs12 \
-            -P ${MACOS_INSTALLER_PASS} \
-            -T /usr/bin/pkgbuild
+          # security import installer.p12 -k build.keychain \
+          #   -t cert -f pkcs12 \
+          #   -P ${MACOS_INSTALLER_PASS} \
+          #   -T /usr/bin/pkgbuild
           security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${MACOS_KEYCHAIN_PASS} build.keychain
-          if [[ "${{ matrix.builds.name }}" == "macos-arm64" ]]; then
-            echo "Add codesign extra args for ${{ matrix.builds.name }}"
-            OSX_CODESIGN_EXTRAS="--entitlements ${GITHUB_WORKSPACE}/applications/minotari_node/osx-pkg/entitlements.xml"
-          fi
-          cd buildtools
-          export target_release="target/${{ matrix.builds.target }}/${{ env.TS_BUILD }}"
-          mkdir -p "${{ runner.temp }}/osxpkg"
-          export tarball_parent="${{ runner.temp }}/osxpkg"
-          export tarball_source="${{ env.TARI_NETWORK_DIR }}"
-          ./create_osx_install_zip.sh unused nozip
+
+          # if [[ "${{ matrix.builds.name }}" == "macos-arm64" ]]; then
+          #   echo "Add codesign extra args for ${{ matrix.builds.name }}"
+          #   OSX_CODESIGN_EXTRAS="--entitlements ${GITHUB_WORKSPACE}/applications/minotari_node/osx-pkg/entitlements.xml"
+          # fi
+
+          # cd buildtools
+          # export target_release="target/${{ matrix.builds.target }}/${{ env.TS_BUILD }}"
+
+          # mkdir -p "${{ runner.temp }}/osxpkg"
+          # export tarball_parent="${{ runner.temp }}/osxpkg"
+          # export tarball_source="${{ env.TARI_NETWORK_DIR }}"
+          # ./create_osx_install_zip.sh unused nozip
+
           ARRAY_FILES=( $(echo ${TS_FILES} | jq --raw-output '.[]' | awk '{ print $1 }') )
-          find "${GITHUB_WORKSPACE}/${target_release}" \
-            -name "randomx-*" -type f -perm -+x \
-            -exec cp -vf {} "${{ runner.temp }}/osxpkg/${{ env.TARI_NETWORK_DIR }}/runtime/" \;
-          FILES_DIAG_UTILS=( \
-            $(find "${GITHUB_WORKSPACE}/${target_release}" \
-                -name "randomx-*" -type f -perm -+x \
-                  -exec sh -c 'echo "$(basename "{}")"' \; \
-              ) \
-          )
-          ARRAY_FILES+=(${FILES_DIAG_UTILS[@]})
+
+          # find "${GITHUB_WORKSPACE}/${target_release}" \
+          #   -name "randomx-*" -type f -perm -+x \
+          #   -exec cp -vf {} "${{ runner.temp }}/osxpkg/${{ env.TARI_NETWORK_DIR }}/runtime/" \;
+          #   FILES_DIAG_UTILS=( \
+          #     $(find "${GITHUB_WORKSPACE}/${target_release}" \
+          #       -name "randomx-*" -type f -perm -+x \
+          #         -exec sh -c 'echo "$(basename "{}")"' \; \
+          #     ) \
+          # )
+          # ARRAY_FILES+=(${FILES_DIAG_UTILS[@]})
+
+          # Codesign all files in ARRAY_FILES
           for FILE in "${ARRAY_FILES[@]}"; do
+            # Codesign
             codesign --options runtime --force --verify --verbose --timestamp ${OSX_CODESIGN_EXTRAS} \
-              --prefix "${{ env.TS_BUNDLE_ID_BASE }}.${{ env.TS_FILENAME }}." \
-              --sign "Developer ID Application: $MACOS_APPLICATION_ID" \
-              "${{ runner.temp }}/osxpkg/${{ env.TARI_NETWORK_DIR }}/runtime/$FILE"
+              --sign "Developer ID Application: ${MACOS_APPLICATION_ID}" \
+              "${{ env.MTS_SOURCE }}/${FILE}"
+
+            # Verify
             codesign --verify --deep --display --verbose=4 \
-              "${{ runner.temp }}/osxpkg/${{ env.TARI_NETWORK_DIR }}/runtime/$FILE"
-            cp -vf "${{ runner.temp }}/osxpkg/${{ env.TARI_NETWORK_DIR }}/runtime/$FILE" \
-              "${{ env.MTS_SOURCE }}"
+              "${{ env.MTS_SOURCE }}/${FILE}"
+
+            # cp -vf "${{ runner.temp }}/osxpkg/${{ env.TARI_NETWORK_DIR }}/runtime/$FILE" \
+            #   "${{ env.MTS_SOURCE }}"
           done
-          distDirPKG=$(mktemp -d -t ${{ env.TS_FILENAME }})
-          echo "${distDirPKG}"
-          echo "distDirPKG=${distDirPKG}" >> $GITHUB_ENV
-          TS_Temp=${{ env.TS_FILENAME }}
-          TS_BUNDLE_ID_VALID_NAME=$(echo "${TS_Temp//_/-}")
-          # Strip apple-darwin
-          TS_ARCH=$(echo "${${{ matrix.builds.target }}//-apple-darwin/}")
-          pkgbuild --root "${{ runner.temp }}/osxpkg/${{ env.TARI_NETWORK_DIR }}" \
-            --identifier "${{ env.TS_BUNDLE_ID_BASE }}.pkg.${TS_BUNDLE_ID_VALID_NAME}" \
-            --version "${TARI_VERSION}" \
-            --install-location "/tmp/tari" \
-            --scripts "${{ runner.temp }}/osxpkg/${{ env.TARI_NETWORK_DIR }}/scripts" \
-            --sign "Developer ID Installer: ${MACOS_INSTALLER_ID}" \
-            "${distDirPKG}/${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg"
+
+          # distDirPKG=$(mktemp -d -t ${{ env.TS_FILENAME }})
+          # echo "${distDirPKG}"
+          # echo "distDirPKG=${distDirPKG}" >> $GITHUB_ENV
+          # TS_Temp=${{ env.TS_FILENAME }}
+          # TS_BUNDLE_ID_VALID_NAME=$(echo "${TS_Temp//_/-}")
+          # # Strip apple-darwin
+          # TS_ARCH=$(echo "${${{ matrix.builds.target }}//-apple-darwin/}")
+          # pkgbuild --root "${{ runner.temp }}/osxpkg/${{ env.TARI_NETWORK_DIR }}" \
+          #   --identifier "${{ env.TS_BUNDLE_ID_BASE }}.pkg.${TS_BUNDLE_ID_VALID_NAME}" \
+          #   --version "${TARI_VERSION}" \
+          #   --install-location "/tmp/tari" \
+          #   --scripts "${{ runner.temp }}/osxpkg/${{ env.TARI_NETWORK_DIR }}/scripts" \
+          #   --sign "Developer ID Installer: ${MACOS_INSTALLER_ID}" \
+          #   "${distDirPKG}/${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg"
+
+          echo "Archive ${{ env.BINFILE }} too ${{ env.BINFILE }}.zip"
+          cd "${{ env.MTS_SOURCE }}"
+          echo "Compute files shasum"
+          ${SHARUN} * >> "${{ env.BINFILE }}.sha256"
+          echo "Show the shasum"
+          cat "${{ env.BINFILE }}.sha256"
+          echo "Checksum verification for files is "
+          ${SHARUN} --check "${{ env.BINFILE }}.sha256"
+          #7z a "${{ env.BINFILE }}.zip" *
+          ditto -c -k --keepParent "*" "${{ env.BINFILE }}.zip"
+
           echo -e "Submitting to Apple...\n\n"
           xcrun notarytool submit \
-            "${distDirPKG}/${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg" \
+            "${{ env.BINFILE }}.zip" \
             --apple-id "${MACOS_NOTARIZE_USERNAME}" \
             --password ${MACOS_NOTARIZE_PASSWORD} \
             --team-id ${MACOS_ASC_PROVIDER} \
@@ -469,25 +491,35 @@ jobs:
           requestUUID=$(tail -n5 notarisation.result | grep "id:" | cut -d" " -f 4)
           requestSTATUS=$(tail -n5 notarisation.result | grep "\ \ status:" | cut -d" " -f 4)
           if [[ ${requestUUID} == "" ]] || [[ ${requestSTATUS} != "Accepted" ]]; then
-            echo "## status: ${requestSTATUS} - could not notarize - ${requestUUID} - ${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg"
+            echo "## status: ${requestSTATUS} - could not notarize - ${requestUUID} - ${{ env.BINFILE }}.zip"
             exit 1
           else
-            echo "Notarization RequestUUID: ${requestUUID}"
-            echo -e "\nStapling package...\
-              ${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg\n"
-            xcrun stapler staple -v \
-              "${distDirPKG}/${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg"
+            echo "Notarization RequestUUID: ${requestUUID} - can't stapler archives"
+            # echo -e "\nStapling package...\
+            #   ${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg\n"
+            # xcrun stapler staple -v \
+            #   "${distDirPKG}/${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg"
           fi
-          cd ${distDirPKG}
-          echo "Compute pkg shasum"
-          ${SHARUN} "${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg" \
-            >> "${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg.sha256"
-          cat "${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg.sha256"
-          echo "Checksum verification for pkg is "
-          ${SHARUN} --check "${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg.sha256"
+
+          # cd ${distDirPKG}
+          # echo "Compute pkg shasum"
+          # ${SHARUN} "${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg" \
+          #   >> "${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg.sha256"
+          # cat "${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg.sha256"
+          # echo "Checksum verification for pkg is "
+          # ${SHARUN} --check "${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg.sha256"
+
+          echo "Compute archive shasum"
+          ${SHARUN} "${{ env.BINFILE }}.zip" >> "${{ env.BINFILE }}.zip.sha256"
+          echo "Show the shasum"
+          cat "${{ env.BINFILE }}.zip.sha256"
+          echo "Checksum verification archive is "
+          ${SHARUN} --check "${{ env.BINFILE }}.zip.sha256"
 
       - name: Artifact upload for macOS pkg
-        if: startsWith(runner.os,'macOS')
+        # Disabled
+        if: ${{ false }}
+        # if: startsWith(runner.os,'macOS')
         continue-on-error: true
         uses: actions/upload-artifact@v4
         with:
@@ -590,6 +622,7 @@ jobs:
           cargo audit bin *tari*
 
       - name: Archive and Checksum Binaries
+        if: ${{ ! (( startsWith(runner.os,'macOS') ) && ( env.MACOS_APPLICATION_CERT != '' )) }}
         shell: bash
         run: |
           echo "Archive ${{ env.BINFILE }} too ${{ env.BINFILE }}.zip"
